module.exports = Object.freeze({
  JSON: 'json',
  XML: 'xml',
  JOB_SCHEDULER: 10,
  SCHEDULE_TASK_RUNNING: '1',
  SCHEDULE_TASK_FAILED: '2',
  SCHEDULE_TASK_COMPLETED: '3',
  PULL_SCHEDULE: '1',
  PUSH_SCHEDULE: '2',
  HTTP_SUCCESS: 200,
  HTTP_CREATED: 201,
  HTTP_BAD_REQUEST: 400,
  HTTP_UN_AUTHORISED: 401,
  HTTP_NOT_FOUND: 404,
  HTPP_INTERNAL_SERVER: 500
})
